env:
  browser: true
  es6: true
  node: true
  jest/globals: true

extends:
  - 'indico'
  - 'indico/babel'
  - 'indico/react'
  - 'indico/prettier'
  - 'prettier/babel'
  - 'prettier/react'
  - 'plugin:jest/recommended'

plugins:
  - jest

settings:
  react:
    version: latest

rules:
  # disable no-unresolved since we don't install the deps
  # of our react example app
  import/no-unresolved: off
